name: Build and Release MAUI App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x # Updated to .NET 9

    - name: Install MAUI Workloads
      run: dotnet workload install maui

    - name: Restore Dependencies
      run: dotnet restore -p:TargetFramework=net9.0-android # Updated to net9.0

    - name: Publish Android App
      run: dotnet publish -c Release -f net9.0-android -p:TargetFramework=net9.0-android /p:AndroidPackageFormat=apk # Updated to net9.0

    - name: Upload APK Installer
      uses: actions/upload-artifact@v4
      with:
        name: ScoreKeeper-Installer
        path: |
          **/*.apk
